### ISSUE TITLE
请问post参数用json格式怎么发？

### ISSUE THREAD

**Issue by freechw** [myleo1/wechat-work-pusher#1]
通过webhook发送，怎么设置 post的参数呢？
还有header怎么设置？ 
这方面不太懂，还请指教。

**Comment by freechw** [comment]
也就是类似企业微信机器人webhook那种方式。

**Comment by myleo1** [comment]
1.接口是采用application/x-www-form-urlencode进行发送的，也就是表单，而非json
2.关于header的设置：key为Cookie val为session=token token是在config.json里配置的

**Comment by freechw** [comment]
好的，多谢！
